authors:
  Marc Bielert:
    name: Marc Bielert        # Author name
    description: circus-pedagoge, founder of NICA e.V. # Author description
    avatar: https://avatars.githubusercontent.com/u/2739380         # Author avatar
    url: www.eigenarts-halle.de            # Author website URL